### ISSUE TITLE
Wrapper for 3D engine: enhancement for Unity 3D

### ISSUE THREAD

**Issue by Vytek** [networkprotocol/yojimbo#53] opened 2017-06-14 09:05 UTC
I think that is very important to create a wrapper for 3D Engine: Unity 3D will be the perfect 3D engine to start. 

It is possible to start a Patreon campaign where I would like to contribute.

**Comment by gafferongames** [comment] 2017-06-15 18:56
I think this is a good idea, but I need to finish the yojimbo in C++ first before we can consider how it is used in C# from Unity. I will re-open this at the appropriate time. Stay tuned.

**Comment by DominaVR** [comment] 2017-07-17 17:36
the VR devs strongly need it. it could boost the current social VR comunity!

**Comment by gafferongames** [comment] 2017-07-17 17:46
Great idea!

**Comment by Vytek** [comment] 2017-07-18 07:57
These is some tutorials how to create a plugin for Unity:

* http://www.alanzucconi.com/2015/10/11/how-to-write-native-plugins-for-unity/
* http://ericeastwood.com/blog/17/unity-and-dlls-c-managed-and-c-unmanaged

**Comment by gafferongames** [comment] 2017-07-18 17:29
If somebody would like to take this on as a project, I'm all for it, but I won't have time to do this myself anytime soon.

**Comment by codemaster** [comment] 2017-07-19 05:59
I work in Unity 3D daily as a game developer and would be happy to take a peek into this, albeit I only have a tiny amount of spare cycles per week and I don't anticipate us using this for our projects anytime soon (darn :))

A good point to start with this is getting it simply importing into Unity and then getting a super basic example to work. Correct?

It's a bit harder because unmanaged C++ types can't be directly utilized within managed C# code, but we can always resort to passing through primitive types with a nice Unity wrapper to facilitate.

Let me know if anyone has any recommendations, suggestions, or wants and I'll try to take a look sooner than later.

Thanks!

**Comment by Vytek** [comment] 2017-07-19 09:46
I am very interesting to the project, but I don't have the correct skill :-( I write some advise here: https://github.com/networkprotocol/yojimbo/issues/53#issuecomment-315987864

See also: 
https://docs.unity3d.com/Manual/PluginsForDesktop.html

If you want a Beta Tester I am here!

**Comment by gafferongames** [comment] 2017-07-19 22:35
@codemaster I think the biggest challenge here is that the message serialization for yojimbo is based around C++ template metaprogramming, and would not port easily to C#. The trick would be working out how people in C# read and write serialize functions in C#, such that they work properly with the rest of the yojimbo runtime in C++. Non-trivial.

**Comment by codemaster** [comment] 2017-07-20 03:48
Thanks for the info, @gafferongames.

My thoughts so far is that we could potentially convert C# objects to a byte array using [BinaryFormatter](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.formatters.binary.binaryformatter.aspx) and submit this byte array directly into the serializer/stream or via a special object/wrapper. Do you think this may work?

What additional strategies do you think we can utilize to bridge that C#/C++ gap on serializing messages to the stream?

**Comment by gafferongames** [comment] 2017-07-20 04:58
Well it would work, but it wouldn't be really efficient. Part of what makes yojimbo good is the bitpacker for messages that lets you serialize small message data really efficiently. It would be a shame to pad that up to bytes.

**Comment by codemaster** [comment] 2017-07-20 05:03
Thanks for the quick response.
Let me do a bit of reading to see if this is possible, I would hate to not take advantage of the nice templating that you provided.

I know C++ objects in C# are mostly a no-no, but I wonder if C# objects can be used a bit easier in C++ :)

**Comment by gafferongames** [comment] 2017-07-20 05:05
I think you could provide a way to implement C# objects that are wrapped by a C++ message type, and  then implement serialize read/write/measure in C#. The question is then, how to best do that, since C# generics are not as efficient as C++ templates in optimizing code, but it's still good to write one serialize function vs. separate read/write/measure functions. Code generation?

**Comment by gafferongames** [comment] 2017-07-20 05:09
Basically, the problem is how to implement unified serialization in C#, is it possible without code generation while still providing optimized read/write/measure serialize functions as efficient as hand-crafted code? I'm not sure.

**Comment by gafferongames** [comment] 2017-07-24 04:04
Closing this out. I support people who would like to do this, but I don't have time to do it myself.

**Closed by gafferongames** 2017-07-24 04:04 UTC

**Comment by FrankAustinK** [comment] 2017-07-26 17:48
@codemaster I'd like to follow, and potentially participate, if this project is going to happen.

**Comment by codemaster** [comment] 2017-07-26 17:53
@ItsAustinK thanks! :)
Happy work on this, but I think @gafferongames mentioned a really good, difficult limitation: having objects cross that C# -> C++ barrier and take advantage of the templated functions. So far, I have yet to think of or find any good solutions to this :(

**Comment by marekhanzlik** [comment] 2017-10-24 20:46
@codemaster Jackson Dunstan is doing a series about how to write everything in C++ instead of C# and he uses Object Handles there to pass objects from C# to C++ so maybe that can be usable.
Object Handles http://jacksondunstan.com/articles/3908
Whole series link http://jacksondunstan.com/articles/3938

**Comment by richterk** [comment] 2019-12-02 06:40
Honestly, if serialization is the only problem, couldn't you just define a quick serialization paradigm?  Obviously, you don't want to use JSON.  It's too verbose, but you could serialize a string, and map it to a message.  Fortunately, Yojimbo has a cleanly defined format for messages.  I'm just getting into the library, but at a high level, I think it's very doable.  I would need to dig in and understand the message format better.   If you could cleanly define the packet format (Header, Crypto, Message, Footer, etc), then you could receive a byte array on the server that gets mapped to a common object, and then processed in order.  If you can define a reasonable message structure, then you don't need a hard dependency between the server and client stream object.  Again, I know very little about the message structure right now, but I'd be happy to help build this, if @gafferongames is available to consult on some of the nitty gritty details of the library.  Campfire Studios is also looking at this to be the game server implementation for our Ignition Engine.

**Comment by erdinckaya** [comment] 2019-12-02 07:42
Hi @richterk 

If you have anytime you can check this repo https://github.com/netcode-io/yojimbo.net.
It is a wrapper for C# and I have created a simple game client and server with that repo for Unity. The result is perfect, it works. May be it helps you. 

Here you can find the example repos.
https://github.com/erdinckaya/prometheus - for Client
https://github.com/erdinckaya/themis - for Server

Last time I checked, the only thing that is missing is yojimbo.net didn't implemented secure connection, however you can define your secure server to establish secure connection.
