### ISSUE TITLE
Block Messages acking delayed

### ISSUE THREAD

**Issue by grynca** [networkprotocol/yojimbo#105] opened 2018-10-16 10:57 UTC
Hello,
i have encountered a possible bug. While sending Block Messages from server to client acking seems to be somehow delayed, leading to crash when ReliableOrderedChannel::m_messageSendQueue becomes full.
I have created minimal bug case, sending Block Messages with 1 byte payload:

```
void test_reliable_ack_delay_bug() {
    double time = 100.0;
    ClientServerConfig config;
    //const int MaxPacketSize = 1024 * 1024;
    //const int MaxBlockSize = 1024 * 1024;
    //config.maxPacketSize = MaxPacketSize;
    //config.maxPacketFragments = 256;
    config.numChannels = 1;
    config.channel[0].type = yojimbo::CHANNEL_TYPE_RELIABLE_ORDERED;
    //config.channel[0].maxBlockSize = MaxBlockSize;
    //config.channel[0].blockFragmentSize = 500;
    //config.channel[0].sentPacketBufferSize = 4096;
    //config.channel[0].blockFragmentResendTime = 0.25f;
    //config.channel[0].messageResendTime = 3.0f;
    uint8_t privateKey[KeyBytes];
    memset(privateKey, 0, KeyBytes);
    Server server(GetDefaultAllocator(), privateKey, Address("127.0.0.1", ServerPort), config, adapter, time);
    server.Start(1/*MaxClients*/);
    check(server.IsRunning());
    uint64_t clientId = 0;
    random_bytes((uint8_t*)&clientId, 8);
    Client client(GetDefaultAllocator(), Address("0.0.0.0"), config, adapter, time);
    Address serverAddress("127.0.0.1", ServerPort);
    client.InsecureConnect(privateKey, clientId, serverAddress);
    const double deltaTime = 0.1;
    Client * clients[] = { &client };
    Server * servers[] = { &server };

    while (true)
    {
        PumpClientServerUpdate(time, clients, 1, servers, 1);
        if (client.ConnectionFailed())
            break;
        if (!client.IsConnecting() && client.IsConnected() && server.GetNumConnectedClients() == 1)
            break;
    }
    check(!client.IsConnecting());
    check(client.IsConnected());
    check(server.GetNumConnectedClients() == 1);
    check(client.GetClientIndex() == 0);
    check(server.IsClientConnected(0));
    PumpClientServerUpdate(time, clients, 1, servers, 1);
    check(!client.IsDisconnected());

    while (true)
    {
    // message sv -> cl
        TestBlockMessage *testBlockMessage = (TestBlockMessage *)server.CreateMessage(0, TEST_BLOCK_MESSAGE);
        uint8_t *blockData = server.AllocateBlock(0, 1);
        server.AttachBlockToMessage(0, testBlockMessage, blockData, 1);
        server.SendMessage(0, 0, testBlockMessage);

        // Normal message -> WORKS
        //TestMessage *testMessage = (TestMessage *)server.CreateMessage(0, TEST_MESSAGE);
        //server.SendMessage(0, 0, testMessage);


    // message cl -> sv
        //TestBlockMessage *testBlockMessage2 = (TestBlockMessage *)client.CreateMessage(TEST_BLOCK_MESSAGE);
        //uint8_t *blockData2 = client.AllocateBlock(1);
        //client.AttachBlockToMessage(testBlockMessage2, blockData2, 1);
        //client.SendMessage(0, testBlockMessage2);

        PumpClientServerUpdate(time, clients, 1, servers, 1);

        Message *message = client.ReceiveMessage(0);
        if (message)
        {
            check(message);
            client.ReleaseMessage(message);
        }
    }
    client.Disconnect();
    server.Stop();
}
```

I also tested sending messages the other way around (from client to server, now commented out), because at first i thought that maybe there are no messages transporting acks, but it did not help. 
It turns out that out yojimbo client is still sending empty messages containing acks even when i am not sending anything.
Normal "non-block" messages in same scenario seems to work nicely.
If it turns out to be a bug, please point me in some direction as i am willing to look into the issue and debug it.

**Comment by gafferongames** [comment] 2018-10-16 15:42
Ah looks like a real bug! Yes, if the block message sending has a problem, it will block the sending of all other messages on that channel, since the channel is reliable/ordered.

Can you please create a pull request with your test added, and #if 0 / #endif or commented out, so somebody can look into this.

Related to this, does somebody have time to look into this bug?

Thank you for the repro!

**Comment by gafferongames** [comment] 2018-10-16 15:44
My guess is that the one byte block is not received, hence it stalls out the queue. Try turning on YOJIMBO_DEBUG_SPAM 1, and compare a working vs. a not working case according to logs that show up, and I think this will be illuminative.

It's going to be one of two things:

1. The sender doesn't get acks for the block, thus the server stalls.
2. The receiver doesn't transition properly to thinking it has received the block, thus stalling out the sender.

I suspect most likely it is #2, but you can't really be sure without debugging further.

**Comment by gafferongames** [comment] 2018-10-16 15:45
ps. The ack system underneath is working, the problem will be in the ReliableOrderedChannel and how it handles the sending/receiving of the one byte block. It's likely that there is an edge case w. the one byte block which is triggering bad behavior.

Once again, thanks for finding this excellent repro!

**Comment by gafferongames** [comment] 2019-04-14 16:35
Hey, I've looked into this. Block messages are different to regular messages. the behavior being tested demonstrates that sending a 1 byte block message every frame eventually you can't send any more blocks. This is to be expected, since it takes more than one frame to properly send, receive and ack a block message. Not a bug!

Block messages are designed for infrequent sending.

**Closed by gafferongames** 2019-04-14 16:35 UTC
Labels: help wanted
