### ISSUE TITLE
yojimbo seems like overload while I keep sending data stably with 110ms delay

### ISSUE THREAD

**Issue by adzhang** [networkprotocol/yojimbo#54] opened 2017-06-15 11:47 UTC
![image](https://user-images.githubusercontent.com/5301510/27179925-6d25796a-5203-11e7-8c0e-3e84d021ba58.png)

**Comment by gafferongames** [comment] 2017-06-15 14:38
Hi, I need more information. What's going on exactly?

**Comment by adzhang** [comment] 2017-06-15 15:19
I make a echo server to test rtt between tcp and yojimbo. I randomly send 100-300 Bytes packets at 60 frequency. It does well until I set the delay to 110 milliseconds.

**Comment by adzhang** [comment] 2017-06-15 15:25
`def client_main():

    udp_client = YJB_UdpClient("xx.xx.xx.xx", 40000)
    if udp_client.create() == False:
        return

    msgs = []
    msg1 = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    msgs.append(msg1)
    msgs.append(msg1*2)
    msgs.append(msg1*3)
    packet = {"seq":0, "time":0, "data":msgs}
    def send_data():
        import json
        packet["seq"] += 1
        packet["time"] = time.time()
        packet["data"] = msgs[packet["seq"]%3]
        json_str = json.dumps(packet)
        SendMsg(json_str, len(json_str))

    logic_frame = 60
    logic_frame_length = 1.0/logic_frame
    accumilated_time = 0
    delta_time = time.time()
    while True:
        now = time.time()
        accumilated_time += now-delta_time
        delta_time = now

        while accumilated_time > logic_frame_length:
            accumilated_time -= logic_frame_length
            send_data()
            udp_client.update(logic_frame_length)

        timeout = logic_frame_length-accumilated_time
        time.sleep(timeout)


    udp_client.destroy()`

**Comment by gafferongames** [comment] 2017-06-15 15:31
Are you using a port of yojimbo to a particular language, or a wrapper? I don't recognize the API above.

**Comment by gafferongames** [comment] 2017-06-15 15:32
Show me your channel/connection configuration. I want to see how your message channels are configured. I also need to know what version of yojimbo you are on. Is it the latest source?

**Comment by adzhang** [comment] 2017-06-15 15:41
I make a wrapper by Python. This is the udp_client.update function.
`int UdpClientContext::Update( float deltaTime )
{
    if ( quit )
    {
        CloseUdpClient();
        return 1;
    }
    clientTransport->ReadPackets();

    client->ReceivePackets();

    processMessage();

    client->SendPackets();

    clientTransport->WritePackets();

    client->CheckForTimeOut();

    time += deltaTime;

    client->AdvanceTime( time );

    clientTransport->AdvanceTime( time );

    if ( client->ConnectionFailed() )
        return 1;

    return 0;
}`

**Comment by adzhang** [comment] 2017-06-15 15:46
I use the ordered channel. But my version is v0.3.0-preview10. Is there any bug fix after that version?

**Comment by gafferongames** [comment] 2017-06-15 15:49
Ah I see that you are using the old version of libyojimbo (last release). Please update to the current source code, and let's see how it goes from that point. It has a slightly diffirent API. Transport classes have gone away, for example.

**Comment by gafferongames** [comment] 2017-06-15 15:49
Yes. yojimbo has a complete rewrite and is a totally different API now. Lots of bugfixes. Completely different internal implementation. New release imminent.

**Comment by adzhang** [comment] 2017-06-15 15:51
This is my Message define. I am a little confuse. Can you show me the bugfiex?
`template <typename Stream> bool Serialize( Stream & stream )
{        
    serialize_bits( stream, sequence, 16 );
    serialize_double(stream, time);
    serialize_bits( stream, iSize, 16);
    if( iSize > MAX_NORMAL_MSG_SIZE )
        return false;

    if ( Stream::IsReading )
    {
        cData = new uint8_t[iSize];
        serialize_bytes(stream, cData, iSize);
    }
    else
    {
        if( iSize > 0 )
        {
            serialize_bytes(stream, cData, iSize);
        }
    }
    return true;
}`

**Comment by gafferongames** [comment] 2017-06-15 15:55
I can't point to a specific bugfix. My point is that since yojimbo has completely been rewritten since the version you are on, my preference to help you track down and fix this would be to do so in the latest version, not the old one.

**Comment by adzhang** [comment] 2017-06-15 15:55
When this happens, should I take the initiative to slow down the frequency?

**Comment by gafferongames** [comment] 2017-06-15 15:56
I don't have enough information yet to answer your questions. Please provide me with a complete sample program that I can run that reproduces your problem.

**Comment by adzhang** [comment] 2017-06-15 16:00
ok. I'll pull the latest version later.

**Comment by gafferongames** [comment] 2017-06-15 16:10
Great. ps. My gut feeling is that you may be sending messages that are too large. Try sending smaller messages and see if this problem still persists. At least then we can start to identify what is going on.

**Comment by adzhang** [comment] 2017-06-16 04:57
It's normal until I set delay up to 100 milliseconds. 
I use tc command:
tc qdisc add dev eth1 root netem delay 75ms 5ms 1% loss 0.5%

I think, when the delay reaches 100ms, its redundancy is as high as six times(60 frequency). It overloaded if I keep sending 100-300Bytes messages. Are there Related solutions in the latest release? Or any feedback to tell me slow down the sending frequency.

**Comment by gafferongames** [comment] 2017-06-16 05:08
I can look into this if you provide me with a sample program that reproduces this, plus instructions on how to run it. Otherwise, I don't have enough information to diagnose. Sorry!

**Comment by gafferongames** [comment] 2017-06-16 18:03
Closing issue for now. I'll re-open once I get a test program.

**Closed by gafferongames** 2017-06-16 18:03 UTC

**Comment by gafferongames** [comment] 2017-06-21 15:55
You should find this resolved in latest head revision. Please update.
